Adding Code to remove exception
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point